GUI_TITLE = "Computer Network Project"
BTN_SEND_TCP_TXT = "TCP"
BTN_SEND_UDP_TXT = "UDP"
BTN_SEND_BOTH_TXT = "BOTH"
SEND_BTN_TXT = "Send"

TXT_BOX_BG = "black"
TXT_BOX_TEXT_COLOR = "#2bbf21"
TXT_BOX_TCP_TXT_COLOR = "#FEBD1A"
TXT_BOX_UDP_TXT_COLOR = "#CC00FF"


DEFAULT_UDP_PORT = 2000
DEFAULT_TCP_PORT = 4000

ENCODING = 'utf-8'

TCP_LABEL = "TCP Socket"
UDP_LABEL = "UDP Socket"

IP_LABEL = "IP Address"
DEFAULT_IP = "Input Address"
TCP_PORT_LABEL = "TCP Port"
UDP_PORT_LABEL = "UDP Port"

TITLE_LABEL = "Team Name"
DEFAULT_SERVER_BIND = ""
DEFAULT_CLIENT_BIND = "localhost"
SERVER_WAITING_TIME = 0.1


APP_HEADER_LEN = 1
TYPE_TEXT_MSG = b'\x00'
TYPE_FILE_TRANSFER = b'\x01'

PACKET_SIZE = 1024
